#!/usr/bin/env python3
"""Unpack a Claude Design export into the files the frontend actually ships.

A .dc.html export is self-extracting: a manifest of gzip+base64 assets plus a
page template. Everything is inlined, including ~500 KB of base64 webfonts,
which is fine for a preview and far too heavy for a render-blocking stylesheet.

This script pulls the export apart so the site can use it:

    python3 design/extract.py "design/Cory DeGarmo.dc.html"

It writes frontend/src/styles/tokens.css, frontend/src/styles/fonts.css and
frontend/public/fonts/*.woff2, and drops the component bundle and template into
a scratch directory for reference when porting a changed component to TSX.

The components themselves are ported by hand into frontend/src/ds/ - the export
is compiled React.createElement against a global namespace, and this project is
React 19 + TypeScript. Diff the scratch bundle against src/ds/ after a
regenerate to see what actually moved.
"""

import base64
import gzip
import json
import pathlib
import re
import sys

KEEP_SUBSETS = {"latin", "latin-ext"}
ROOT = pathlib.Path(__file__).resolve().parent.parent


def block(src: str, kind: str) -> str | None:
    m = re.search(r'<script type="__bundler/%s">(.*?)</script>' % kind, src, re.S)
    return m.group(1).strip() if m else None


def main(export: pathlib.Path) -> None:
    src = export.read_text(encoding="utf-8")
    manifest = json.loads(block(src, "manifest") or "{}")
    names = {e["uuid"]: e["id"] for e in json.loads(block(src, "ext_resources") or "[]")}

    scratch = ROOT / "design" / "_unpacked"
    scratch.mkdir(exist_ok=True)

    styles = None
    for uuid, entry in manifest.items():
        raw = base64.b64decode(entry["data"])
        if entry.get("compressed"):
            raw = gzip.decompress(raw)
        name = names.get(uuid, uuid).split("/")[-1]
        (scratch / name).write_bytes(raw)
        if name == "styles.css":
            styles = raw.decode("utf-8")
    (scratch / "template.html").write_text(json.loads(block(src, "template") or '""'))

    if styles is None:
        sys.exit("no styles.css in the export")

    # Fonts: one real file per face, latin/latin-ext and upright only.
    faces = re.findall(
        r"/\* (\S+) \*/\s*@font-face \{\s*font-family: '([^']+)';\s*font-style: (\w+);"
        r"\s*font-weight: ([^;]+);\s*font-display: swap;\s*"
        r'src: url\("data:font/woff2;base64,([^"]+)"\)[^;]*;\s*unicode-range: ([^;]+);',
        styles,
    )
    fonts_dir = ROOT / "frontend" / "public" / "fonts"
    fonts_dir.mkdir(parents=True, exist_ok=True)
    blocks = []
    for subset, family, style, weight, b64, unicode_range in faces:
        if subset not in KEEP_SUBSETS or style != "normal":
            continue
        slug = f"{family.lower().replace(' ', '-')}-{weight.strip().replace(' ', '-')}-{subset}.woff2"
        (fonts_dir / slug).write_bytes(base64.b64decode(b64))
        blocks.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight.strip()};\n"
            "  font-display: swap;\n"
            f"  src: url('/fonts/{slug}') format('woff2');\n"
            f"  unicode-range: {unicode_range.strip()};\n"
            "}"
        )

    css_dir = ROOT / "frontend" / "src" / "styles"
    (css_dir / "fonts.css").write_text(
        "/*\n"
        " * Generated by design/extract.py - do not edit by hand.\n"
        " * Latin and latin-ext only, upright only: the design uses no italics.\n"
        " */\n\n" + "\n\n".join(blocks) + "\n"
    )

    # Tokens: everything from the first :root to just before the base element
    # defaults, which live in global.css alongside this site's own additions.
    start = styles.index(":root {")
    end = styles.index("/* Base element defaults")
    (css_dir / "tokens.css").write_text(
        "/*\n"
        " * Design tokens, taken verbatim from the DeGarmo design system export.\n"
        " * Generated by design/extract.py - do not edit by hand. Site-specific\n"
        " * overrides belong in global.css so this file keeps diffing cleanly.\n"
        " *\n"
        ' * Dark is the default; light is opt-in via [data-theme="light"].\n'
        " */\n\n" + styles[start:end].rstrip() + "\n"
    )

    print(f"fonts:  {len(blocks)} faces -> frontend/public/fonts/")
    print("tokens: frontend/src/styles/tokens.css")
    print(f"ref:    {scratch.relative_to(ROOT)}/ (bundle + template, for porting)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(pathlib.Path(sys.argv[1]))
