# Generated by Django 5.2.17 on 2026-08-28 16:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question_set_version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resume', 'Resume'), ('intake_turn', 'Intake turn'), ('document', 'Document'), ('repo', 'Repository'), ('manual', 'Entered by hand')], max_length=20)),
                ('label', models.CharField(help_text='Human-readable description of origin.', max_length=255)),
                ('captured_on', models.DateField()),
                ('uri', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='kb.intakesession')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_turn', to='kb.source')),
            ],
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('filled', models.BooleanField(default=False)),
                ('filled_by_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_gaps', to='kb.intaketurn')),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('Role', 'Role'), ('Project', 'Project'), ('Story', 'Story'), ('Skill', 'Skill'), ('Constraint', 'Constraint')], max_length=20)),
                ('payload', models.JSONField(help_text='The proposed field values.')),
                ('confidence', models.FloatField(help_text='Expected range 0.0-1.0.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_object_id', models.IntegerField(blank=True, help_text='Set when approved and promoted.', null=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='kb.intaketurn')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('recruiter', 'Recruiter'), ('private', 'Private')], default='recruiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('platform', 'Platform'), ('protocol', 'Protocol'), ('domain', 'Domain'), ('tool', 'Tool')], max_length=20)),
                ('first_used', models.DateField()),
                ('last_used', models.DateField(blank=True, help_text='Null means currently in use.', null=True)),
                ('depth', models.CharField(choices=[('familiar', 'Familiar'), ('working', 'Working'), ('deep', 'Deep')], max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='kb.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('recruiter', 'Recruiter'), ('private', 'Private')], default='recruiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null means current.', null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('contract', 'Contract'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20)),
                ('summary', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='kb.source')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('recruiter', 'Recruiter'), ('private', 'Private')], default='recruiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Technologies used.', size=None)),
                ('outcome', models.TextField(blank=True, help_text='What it produced or changed.')),
                ('url', models.URLField(blank=True, help_text='Public repo or live site.', null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='kb.role')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='kb.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('recruiter', 'Recruiter'), ('private', 'Private')], default='recruiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('location', 'Location'), ('remote_policy', 'Remote policy'), ('compensation', 'Compensation'), ('role_type', 'Role type'), ('industry', 'Industry'), ('dealbreaker', 'Dealbreaker')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='kb.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('recruiter', 'Recruiter'), ('private', 'Private')], default='recruiter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short internal handle.', max_length=200)),
                ('situation', models.TextField()),
                ('action', models.TextField()),
                ('result', models.TextField()),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='e.g. conflict, failure, leadership, ambiguity, scale.', size=None)),
                ('requires_context', models.BooleanField(default=False, help_text='Fine to tell, but lands badly without framing. Not a visibility level: the answering layer includes these only when a question invites them, rather than in a general summary.')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='kb.project')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='kb.role')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='kb.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
