# Generated by Django 5.2.17 on 2026-08-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('role', 'Role'), ('project', 'Project'), ('education', 'Education'), ('skill', 'Skill'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, help_text='Null = current.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['-start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('interview', 'Interview turn'), ('resume', 'Resume'), ('document', 'Uploaded document'), ('link', 'Link'), ('manual', 'Entered by hand')], max_length=20)),
                ('label', models.CharField(help_text="Human-readable citation, e.g. 'Interview, 12 Aug 2026' or 'resume-2026.pdf, p2'.", max_length=200)),
                ('excerpt', models.TextField(help_text='Verbatim span this source contributed. Shown to the recruiter when they open a citation.')),
                ('uri', models.URLField(blank=True, help_text='Original location, if any.')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The assertion, stated plainly.')),
                ('visibility', models.IntegerField(choices=[(10, 'Public'), (20, 'Recruiter'), (30, 'Private')], db_index=True, default=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text="Extractor's confidence that the source supports this.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Optional grouping. Standalone claims are fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='kb.entity')),
                ('source', models.ForeignKey(help_text='Required. A claim without a source cannot exist.', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='kb.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
