# Generated by Django 5.2.17 on 2026-08-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intaketurn',
            name='question_text',
            field=models.TextField(help_text='Denormalised snapshot of the wording as asked at the time.'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier, referenced by code and seeds.', unique=True)),
                ('text', models.TextField(help_text='The question as asked.')),
                ('category', models.CharField(choices=[('opener', 'Opener'), ('role', 'Role'), ('project', 'Project'), ('story', 'Story'), ('skill', 'Skill'), ('constraint', 'Constraint'), ('closer', 'Closer')], max_length=20)),
                ('target_model', models.CharField(blank=True, choices=[('Role', 'Role'), ('Project', 'Project'), ('Story', 'Story'), ('Skill', 'Skill'), ('Constraint', 'Constraint')], help_text='Which knowledge model this question primarily feeds. Null for openers and closers.', max_length=20, null=True)),
                ('priority', models.IntegerField(help_text='Lower sorts first.')),
                ('active', models.BooleanField(default=True)),
                ('question_set_version', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['priority'],
                'constraints': [models.UniqueConstraint(fields=('key', 'question_set_version'), name='unique_question_key_per_version')],
            },
        ),
        migrations.AddField(
            model_name='intaketurn',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='kb.question'),
        ),
    ]
