# Generated by Django 5.2.17 on 2026-08-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_alter_intaketurn_question_text_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='supporting_quote',
            field=models.TextField(blank=True, help_text='Verbatim span of the answer that justifies this record. What makes the extraction auditable rather than merely plausible.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.SlugField(help_text='Stable identifier, referenced by code and seeds. Unique within a question set, so a later set can reuse it.'),
        ),
        migrations.AddConstraint(
            model_name='intaketurn',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_turn_per_question_in_session'),
        ),
    ]
