# Generated by Django 5.2.17 on 2026-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_extraction_supporting_quote_alter_question_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Why a reviewer turned this down. Kept so a recurring extraction fault is visible as a pattern rather than lost.'),
        ),
    ]
