# Generated by Django 5.2.17 on 2026-08-28 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_extraction_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Technologies used. Empty when the source named none.', size=None),
        ),
        migrations.AlterField(
            model_name='skill',
            name='depth',
            field=models.CharField(blank=True, choices=[('familiar', 'Familiar'), ('working', 'Working'), ('deep', 'Deep')], help_text='Null means the source never stated it. Nullable on purpose: a required enum would force a guess.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='e.g. conflict, failure, leadership, ambiguity, scale. Empty when the source suggested none.', size=None),
        ),
    ]
